kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lvm-controller
  namespace: default
subjects:
- kind: ServiceAccount
  name: lvm-controller
  namespace: default
  # Replace this with the namespace the operator is deployed in.
roleRef:
  kind: ClusterRole
  name: lvm-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: lvm-controller
rules:
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - "storage.k8s.io"
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - "snapshot.storage.k8s.io"
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lvm-controller
  namespace: default
